Add files via upload
ntop/ipt_geofence pull request #7
Opened 2022-03-05 16:36 UTC by leomanne

Adding Continents Support

2022-03-05 16:37 UTC, leomanne commented
Adding Continents support

2022-03-06 17:31 UTC, lucaderi requested changes
The code is in good shape but you should not commit binary or generated files. Please remove them. When you send a PR you need to specify what have you changes and not re-upload the whole project to github

2022-03-06 17:31 UTC, lucaderi commented on Configuration.cpp
> +
Refactor code in order to merge country and continent logic and remove code duplication

2022-03-06 17:31 UTC, lucaderi commented on Configuration.cpp
> +}
Refactor here too

2022-03-06 17:31 UTC, lucaderi commented on NwInterface.cpp
> +  char continent[14];
Why 14 chars? Can you please explain what are the continent acronyms supported?

2022-03-09 10:59 UTC, lucaderi commented
Closing PR as of https://github.com/ntop/ipt_geofence/pull/11

2022-03-09 10:59 UTC, closed without merging